### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by gengzhichen** [tuneflow/so-vits-svc-plugin#2]
这个大概会是啥问题，已经是管理员权限允许的anaconda prompt 和tuneflow
Exception: Failed to generate audio
======================================================
run plugin
DEBUG:pydub.converter:subprocess.call(['ffmpeg', '-y', '-read_ahead_limit', '-1', '-i', 'cache:pipe:0', '-acodec', 'pcm_s16le', '-vn', '-f', 'wav', '-'])
Using cached model
Traceback (most recent call last):
  File "C:\ai\so-vits-svc-plugin\inferencer.py", line 105, in vc_fn
    sampling_rate, audio = audio_from_file(input_audio_path)
  File "C:\ai\so-vits-svc-plugin\inferencer.py", line 77, in audio_from_file
    audio = AudioSegment.from_file(filename)
  File "C:\Users\xxx\anaconda3\envs\tuneflow\lib\site-packages\pydub\audio_segment.py", line 651, in from_file
    file, close_file = _fd_or_path_or_tempfile(file, 'rb', tempfile=False)
  File "C:\Users\xxx\anaconda3\envs\tuneflow\lib\site-packages\pydub\utils.py", line 60, in _fd_or_path_or_tempfile
    fd = open(fd, mode=mode)
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\xxx\\AppData\\Local\\Temp\\tmpy_8by6tlmp3'
Traceback (most recent call last):
  File "C:\ai\so-vits-svc-plugin\plugin.py", line 144, in run
    raise Exception("Failed to generate audio")
Exception: Failed to generate audio

**Comment by 0Liuguosong** [comment]
同样的问题，有没有找到解决办法呢？
